### ISSUE TITLE
card view layout

### ISSUE THREAD

**Issue by charchow** [Open-Source-Medical-Supplies/react-projects-gallery#1]
Kimly: try to get rid of the view button, or place it in line with the category to reduce unnecessary white space/size of card

**Comment by charchow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project Gallery](https://trello.com/c/qM3kDIpO/114-project-gallery)

**Comment by JoshMLeslie** [comment]
I'm gonna go ahead and say no unless you've ideas  where else to put the button 
![image](https://user-images.githubusercontent.com/30437767/84093821-4b981480-a9c9-11ea-806f-8d86d8a49276.png)
