### ISSUE TITLE
Medical Status field: Affiliated With and Reviewed by Tags filter not working

### ISSUE THREAD

**Issue by charchow** [Open-Source-Medical-Supplies/react-projects-gallery#10]
"Affiliated with" and "Reviewed By" tagged projects not showing in attributes filter- they're pulling into the card view fine - filter definition or logic issue?
![medical status](https://user-images.githubusercontent.com/63361740/84446937-b721f200-ac14-11ea-98f0-1388cb3e7b8f.png)

**Comment by charchow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project Library: Medical Status field: Affiliated With and Reviewed by Tags filter not working](https://trello.com/c/Lv98JBQU/139-project-library-medical-status-field-affiliated-with-and-reviewed-by-tags-filter-not-working)

**Comment by JoshMLeslie** [comment]
For both cases - the tag in the **Engineered Project Page** table had the value _Affiliated **w**ith_ and _Reviewed **b**y_ . In the **ProjectsFilterMenu** table had a capital **W** and **B** respectively.

I updated the EPP table to have capitals to match PFM
