### ISSUE TITLE
change default selection for browsing supply cats to single 

### ISSUE THREAD

**Issue by charchow** [Open-Source-Medical-Supplies/react-projects-gallery#11]
change default to one selection with the possibility of selecting multiple categories by pressing control/cmd
-
Name: Gui Cavalcanti
Date: 6/10/2020
Browser: Chrome
Issue: The behavior of the ‘categories’ selection in Project Library allows you to select multiple categories at once - it seems like it’d be more intuitive if it was exclusive. 
Page / Location: Project Library

![project library category selection](https://user-images.githubusercontent.com/63361740/84534347-c017cf80-acb7-11ea-8e58-a0fc19146927.png)

**Comment by JoshMLeslie** [comment]
fixed in c1153d51373d2ed427eebe728a0b19089f15487a
