### ISSUE TITLE
Change text align for Material Name 

### ISSUE THREAD

**Issue by charchow** [Open-Source-Medical-Supplies/react-projects-gallery#12]
Name: Kimly
Date: 06/11/2020
Browser: Chrome
Issue:  Can we center!!! The material text with the material image!? It’s a little awkward for 
Page / Location: Project Libary preview card
![materials centering text example](https://user-images.githubusercontent.com/63361740/84543708-daf33f80-acc9-11ea-9967-aa1b509cc927.png)
![materials centering example](https://user-images.githubusercontent.com/63361740/84543709-daf33f80-acc9-11ea-8f59-42f7b4f0b1d5.png)

**Comment by JoshMLeslie** [comment]
fixed by 11b475de4e43b42800d2dcef954007f08302c4cc
