### ISSUE TITLE
Full card: semantics per Kimly

### ISSUE THREAD

**Issue by charchow** [Open-Source-Medical-Supplies/react-projects-gallery#8]
1. 'Reviewed By', text should be, "Medical Status:"
2. the text from the tags 'Reviewed By' does need to be shown, ex 'Affiliated with: UW Health'
3. Text of Medical Supply Category should, be bold or somehow different from the Title Header Style, and link back to category supply page
4. In Materials List, underneath Material Name, should be hyper formatted text from 'Detail', base 'Bill of Materials'

**Comment by charchow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Full card: semantics](https://trello.com/c/NsaMaNLL/120-full-card-semantics)

**Comment by JoshMLeslie** [comment]
1-3 fixed with c618c58845fbc5a6a8e2d39c4a6a30722e1041ee

**Comment by JoshMLeslie** [comment]
4 fixed with fb47b4abfda5f473f614d599b3c79603277067cc

**Comment by charchow** [comment]
materials carousel is looking a lot better, but Material Name should pull hyper formatted text from 'Detail' field in airtable Supplies base 'Bill of Materials' (which the Engineered Projects looks up the tags for materials from). 
![Screen Shot 2020-06-12 at 4 16 15 PM](https://user-images.githubusercontent.com/63361740/84542773-1f7ddb80-acc8-11ea-9137-eeb110d4a18a.png)

**Comment by charchow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update/add project card materials to pull data from "detail"](https://trello.com/c/2hDfppkF/143-update-add-project-card-materials-to-pull-data-from-detail)

**Comment by charchow** [comment]
looks good now - not sure how 
`      subHeader: data.detail || ''
wasn't loading before, but it's working fine now`
